### ISSUE TITLE
[BUG] - Chrome autofill changes background color for Input component

### ISSUE THREAD

**Issue by twirlse** [nextui-org/nextui#1346]
### Describe the bug

When selecting a value from chrome autocomplete its background changes to lightblue.

### Your Example Website or App

Please see sample at https://github.com/twirlse/nextui-autocomplete-bug

### Steps to Reproduce the Bug or Issue

Create an input that Chrome has autocomplete values for (i.e. email). 
See attached animation.

### Expected behavior

Background color for input should not change.

### Screenshots or Videos

![Animation](https://github.com/nextui-org/nextui/assets/52166/76635bb7-84fc-4896-b5e5-1df12cd4c67f)

### Operating System Version

Windows

### Browser

Chrome

**Comment by jguddas** [comment]
> Background color for input should not change.

Strongly disagree, we should definitely reflect user action.

Maybe do it in a prettier way tho :)

**Comment by twirlse** [comment]
Well, at least it should look nice.
I haven't seen (or noticed) this behavior on other sites.

**Comment by jrgarciadev** [comment]
@jguddas Maybe we could take leverage of TailwindCSS autofill pseudo class https://tailwindcss.com/docs/hover-focus-and-other-states#autofill

**Comment by jguddas** [comment]
Sure, do you have a certain background color that we should go for, and should it be applied to the whole `Input` or just the `input` html element?

**Comment by SohamSen15** [comment]
Try to style the input component using the following style:

```css
input:-webkit-autofill,
input:-webkit-autofill:hover, 
input:-webkit-autofill:focus, 
input:-webkit-autofill:active  {
    -webkit-box-shadow: 0 0 0 40px white inset !important;
}
```

This usually removes the autofill colour changes made by the browsers.
