### ISSUE TITLE
[BUG] - Missing peer dependencies

### ISSUE THREAD

**Issue by LIMPIX31** [nextui-org/nextui#1722]
### NextUI Version

2.1.13

### Describe the bug

Many packages don't specify peer dependencies e.g. `framer-motion`, `react-dom`. This is unforgivable when using Yarn.

```
Required package: framer-motion
Required by: @nextui-org/ripple@virtual:ceba9bfd964023b8dcd7e3fb0bc08334b78f754de43a9bc9a22441ded711e140d321ce6bdd612b858cd79cabe0ba332bd1f8311834d6b5e2cfaf293549c17e9e#npm:2.0.21 (via ~/.yarn/__virtual__/@nextui-org-ripple-virtual-0b08af6674/3/.yarn/berry/cache/@nextui-org-ripple-npm-2.0.21-808c9d0c41-10c0.zip/node_modules/@nextui-org/ripple/dist/)

Ancestor breaking the chain: @nextui-org/button@virtual:a532a249b2732ba2285642920474ad3e50dfa13a278b448fce8931835989ff22b7be9e602692b58d3d7b62fda98756b3013cf6e96fa59849b07444bf9e48a6d3#npm:2.0.21
Ancestor breaking the chain: @nextui-org/card@virtual:a532a249b2732ba2285642920474ad3e50dfa13a278b448fce8931835989ff22b7be9e602692b58d3d7b62fda98756b3013cf6e96fa59849b07444bf9e48a6d3#npm:2.0.21

...

Ancestor breaking the chain: @nextui-org/dropdown@virtual:a532a249b2732ba2285642920474ad3e50dfa13a278b448fce8931835989ff22b7be9e602692b58d3d7b62fda98756b3013cf6e96fa59849b07444bf9e48a6d3#npm:2.1.10
Ancestor breaking the chain: @nextui-org/menu@virtual:a532a249b2732ba2285642920474ad3e50dfa13a278b448fce8931835989ff22b7be9e602692b58d3d7b62fda98756b3013cf6e96fa59849b07444bf9e48a6d3#npm:2.0.11
Ancestor breaking the chain: @nextui-org/modal@virtual:a532a249b2732ba2285642920474ad3e50dfa13a278b448fce8931835989ff22b7be9e602692b58d3d7b62fda98756b3013cf6e96fa59849b07444bf9e48a6d3#npm:2.0.23
Ancestor breaking the chain: @nextui-org/navbar@virtual:a532a249b2732ba2285642920474ad3e50dfa13a278b448fce8931835989ff22b7be9e602692b58d3d7b62fda98756b3013cf6e96fa59849b07444bf9e48a6d3#npm:2.0.22
Ancestor breaking the chain: @nextui-org/popover@virtual:a532a249b2732ba2285642920474ad3e50dfa13a278b448fce8931835989ff22b7be9e602692b58d3d7b62fda98756b3013cf6e96fa59849b07444bf9e48a6d3#npm:2.1.9
Ancestor breaking the chain: @nextui-org/system@virtual:a532a249b2732ba2285642920474ad3e50dfa13a278b448fce8931835989ff22b7be9e602692b58d3d7b62fda98756b3013cf6e96fa59849b07444bf9e48a6d3#npm:2.0.10
Ancestor breaking the chain: @nextui-org/tooltip@virtual:a532a249b2732ba2285642920474ad3e50dfa13a278b448fce8931835989ff22b7be9e602692b58d3d7b62fda98756b3013cf6e96fa59849b07444bf9e48a6d3#npm:2.0.24
Ancestor breaking the chain: @nextui-org/use-aria-modal-overlay@virtual:e04f68776c0046de0314e8b625d3f15e00206ca6bb92081254c61cc343babf399c366d19e8626dbb3582a11a3ae499108d643af3ddade84217dbd0aac66e11a8#npm:2.0.5
Ancestor breaking the chain: @nextui-org/use-aria-multiselect@virtual:e4c8c0f2d5ef71fb5532633462851c5d55af795fbd572b04604d3ae62680176e8749987a89d5cff0ac06e3eb57aa60e0ccee4990751d8800f49302a52b2c33ba#npm:2.1.2

```

This is not a critical issue as it can be fixed with `packageExtensions`:

Example:
```yml
packageExtensions:
  '@nextui-org/avatar@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/badge@*':
    peerDependencies:
      framer-motion: '*'
  '@nextui-org/button@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/card@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/chip@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/checkbox@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/code@*':
    peerDependencies:
      framer-motion: '*'
  '@nextui-org/link@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/pagination@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/radio@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/spinner@*':
    peerDependencies:
      framer-motion: '*'
  '@nextui-org/switch@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/user@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/progress@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/input@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/image@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/table@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/spacer@*':
    peerDependencies:
      framer-motion: '*'
  '@nextui-org/divider@*':
    peerDependencies:
      framer-motion: '*'
  '@nextui-org/kbd@*':
    peerDependencies:
      framer-motion: '*'
  '@nextui-org/skeleton@*':
    peerDependencies:
      framer-motion: '*'
  '@nextui-org/scroll-shadow@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/listbox@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/menu@*':
    peerDependencies:
      framer-motion: '*'
      react-dom: '*'
  '@nextui-org/dropdown@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/modal@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/navbar@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/popover@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/system@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/tooltip@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/use-aria-modal-overlay@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/use-aria-multiselect@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/accordion@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/aria-utils@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/framer-transitions@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/react@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/ripple@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/select@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/snippet@*':
    peerDependencies:
      react-dom: '*'
  '@nextui-org/tabs@*':
    peerDependencies:
      react-dom: '*'
```

### Steps to Reproduce the Bug or Issue

1. Run the NextUI and NextJS installation using Yarn 3/4
2. Try to use any component e.g. Button

### Expected behavior

NextUi packages require the necessary peer dependencies, even those required by nested packages

### Operating System Version

Linux

### Browser

Firefox
