### ISSUE TITLE
[BUG] - customizing-colors like  tailwindcss variables 

### ISSUE THREAD

**Issue by MahediAmin** [nextui-org/nextui#2234]
### NextUI Version

2.2.9

### Describe the bug

i can not add color like 
<img width="590" alt="image" src="https://github.com/nextui-org/nextui/assets/26061598/498eb291-aebd-47e3-a0ba-e835f3a10015">
<img width="568" alt="image" src="https://github.com/nextui-org/nextui/assets/26061598/3224070c-97e0-4dc7-b72e-a10ad806db91">

### Steps to Reproduce the Bug or Issue

i have no idea

### Expected behavior

i want to make css variable in my css  file then need to add into tawlind config file. 

### Operating System Version

MacOs

### Browser

Chrome

**Comment by kght6123** [comment]
@MahediAmin When I tried it here, all three patterns below worked fine.
Please tell us more about your environment.

- framework
- Tailwind CSS Version ...etc

If possible, it would be helpful to have a minimal project somewhere that reproduces the problem so we can investigate further.

The following was confirmed with a React project using Vite.

```css
/* src/index.css */
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  /* 1. For rgb(255 115 179 / ‹alpha-value >) */
  /* --color-primary: 255 115 179; */

  /* 2. For hsl(198deg 93% 60% / <alpha-value>) */
  /* --color-primary: 198deg 93% 60%; */

  /* 3. For rgba(255, 115, 179, ‹alpha-value>) */
  --color-primary: 255, 115, 179;
}
```

```ts
// tailwind.config.ts
import { nextui } from "@nextui-org/react";

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./node_modules/@nextui-org/theme/dist/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // 1. Using modern rgb
        // primary: 'rgb(var(--color-primary) / <alpha-value>)',
        // secondary: 'rgb(var(--color-secondary) / <alpha-value>)',
        // 2. Using modern hsl
        // primary: 'hsl(var(--color-primary) / <alpha-value>)',
        // secondary: 'hsl(var(--color-secondary) / <alpha-value>)',
        // 3. Using legacy rgba
        primary: 'rgba(var(--color-primary), <alpha-value>)',
        secondary: 'rgba(var(--color-secondary), <alpha-value>)',
      },
    },
  },
  darkMode: "class",
  plugins: [nextui()],
};
```

```tsx
// src/App.tsx
import "./App.css";

function App() {
  return (
    <>
      <div className="bg-primary w-32 h-32"/>
    </>
  );
}
export default App;
```
