### ISSUE TITLE
[Feature Request] Add selectorButtonPlacement prop to DatePicker component

### ISSUE THREAD

**Issue by maxsynnott** [nextui-org/nextui#3015]
### Is your feature request related to a problem? Please describe.

Currently the DatePicker component always renders the `selectorButton` on the right side of the input and there is no way of changing this placement. 

I suggest adding a prop to allow the placement to be modified

I think this feature is pretty necessary to align with other inputs that are using icons in their `startContent` prop.

### Describe the solution you'd like

I think there should be a new prop on the DatePicker component like so:

```ts
selectorButtonPlacement?: "left" | "right" // default "right"
```

### Describe alternatives you've considered

I've currently hacked around it using css but it's not pretty

```tsx
<DatePicker
	...
	className="date-picker-left-selector-button"
	...
/>
```

```css
.date-picker-left-selector-button [data-slot="inner-wrapper"] {
	flex-direction: row-reverse;
	column-gap: 0;
}

.date-picker-left-selector-button [data-slot="selector-button"] {
	justify-content: start;
}
```

<img width="376" alt="Screenshot 2024-05-17 at 4 29 17 PM" src="https://github.com/nextui-org/nextui/assets/51816032/dd6c37dd-6aa5-4733-b6a1-66fddb3e258a">
