### ISSUE TITLE
[BUG] - Image component doesn't seem to properly follow all CSS properties, can't use object-fit effectively

### ISSUE THREAD

**Issue by Infinitay** [nextui-org/nextui#869]
I was attempting to place an image within a div so that I could have a pre-defined layout on the page. I wanted the div's size to be static. The image should be scaled down if it exceeds the parent div's bounds else remain unchanged. The issue was that when attempting various methods including the accepted solution (with `img` element instead of `Image` component) listed below, it was not working and not properly rescaling.

Assuming my code is correct, I have reason to believe it's NextUI issue. As stated above, the css styling works just fine when using an `img` element rather than the `Image` component given by NextUI. I've tried many things from directly modifying the css to using the built in properties of the `Image` component such as `objectFit`. I couldn't solve my issue until I bothered much later to try it with an `img` element instead.

---

#### This is the actual results. The code and previews below are what was not the intended behavior.

<details>
<summary>Code</summary>

As I said above, I've already tried using properties (`css` and `objectFit`) but they just didn't work and so I attempted to do with by specifying a class inside the global css file. That still didn't work.

### page.tsx
```typescript
<div className="image-container">
	<Image className="image" src={imageURL}>
	</Image>
</div>
```

### globals.css
```css
.main {
	width: 100vw;
	height: 100vh;
	display: flex;
	flex-direction: column;
	justify-content: center;
	align-items: center;
}

.image-container {
	display: flex;
	justify-content: center;
	align-items: center;
	min-width: 50vw;
	min-height: 50vh;
	max-width: 50vw;
	max-height: 50vh;
	border: solid;
}

.image {
	max-width: 100%;
	max-height: 100%;
	object-fit: scale-down;
}
```
</details>

<details>
<summary> ✔ Small image</summary>

![image](https://user-images.githubusercontent.com/6964154/200927779-7519cfd8-8b4c-4eea-8c3a-c65800ea2bfb.png)
</details>

<details>
<summary> ❌ Large landscape image</summary>

![image](https://user-images.githubusercontent.com/6964154/200928491-e88f46f3-a7f4-4ce6-8363-7100d07e4298.png)
</details>

<details>
<summary> ❌ Large portrait image</summary>

![image](https://user-images.githubusercontent.com/6964154/200928557-c1a5f266-7a5b-49d8-8939-a59ca5d27bd2.png)
</details>

#### This is the expected results. The code and previews below are what was intended behavior, and was expecting the same behavior when using NextUI's `Image` component.

<details>
<summary>Code</summary>

The only difference in this version from the code above is changing out `Image` for `img`.

### page.tsx
```typescript
<div className="image-container">
	<img className="image" src={imageURL}>
	</img>
</div>
```

### globals.css
```css
.main {
	width: 100vw;
	height: 100vh;
	display: flex;
	flex-direction: column;
	justify-content: center;
	align-items: center;
}

.image-container {
	display: flex;
	justify-content: center;
	align-items: center;
	min-width: 50vw;
	min-height: 50vh;
	max-width: 50vw;
	max-height: 50vh;
	border: solid;
}

.image {
	max-width: 100%;
	max-height: 100%;
	object-fit: scale-down;
}
```
</details>

<details>
<summary> ✔ Small image</summary>

![image](https://user-images.githubusercontent.com/6964154/200929066-8b489e25-b1f1-4a08-9cb4-4531b98b3509.png)
</details>

<details>
<summary> ✔ Large landscape image</summary>

![image](https://user-images.githubusercontent.com/6964154/200929034-a4c57cfa-4777-4e19-ab7e-2d8109cb6770.png)
</details>

<details>
<summary> ✔ Large portrait image</summary>

![image](https://user-images.githubusercontent.com/6964154/200928979-1f89f706-18b5-42d9-a815-ea68604f6ea8.png)
</details>
