### ISSUE TITLE
[BUG] - With Firefox dark theme, list items render black text on black background

### ISSUE THREAD

**Issue by ajvincent** [nextui-org/nextui#972]
### Describe the bug

I use the Dark theme on Mozilla Firefox.  With the following code, the `<h1>` and `<p>` elements are visible, but the `<li>` elements are not.

I traced this to a theme rule:
```css
ul, ol {
  list-style-type: none;
  color: var(--nextui-colors-foreground);
}
```

### Steps to Reproduce the Bug or Issue

1. In Firefox's settings, go to Settings > General > Language and Appearance > Website appearance and set the theme to Dark.
2. Launch a NextJS application, with the code from Figure 1in pages/test.tsx:
3. Load the localhost/test page.  (Port number may be missing.)

Figure 1.
```tsx
export default function Mockup() : JSX.Element 
{
    return <>
      <h1>React with NextUI experiments</h1>
      <p>Hello World</p>
      <ul>
        <li>This is a list item.</li>
      </ul>
    </>
}
```

I tried using StackBlitz as above, but apparently their Firefox support is in alpha state, and I couldn't open the page in a new tab.

### Expected behavior

The list item should be rendered with visible text.

Potential fix in /styles/global.css:
```css
@media (prefers-color-scheme: dark) {
  body {
    --nextui-colors-foreground: "white"
  }
}
```

### Screenshots or Videos

![Screenshot 2022-12-27 at 17-43-40 Screenshot](https://user-images.githubusercontent.com/1527783/209744219-3ad943f7-7a56-4f63-bf3d-704ab4576bf4.png)

### Operating System Version

Fedora Linux 37

### Browser

Firefox
